import type { Project } from "./types";

export const MyProject: Project[] = [
  {
    id: "1",
    title: "A Renewal Agent 7.0",
    role: "Website Project Manager",
    year: "2025",
    description:
      "Led end-to-end fullstack development using Next.js and Golang. Implemented Docker-based blue-green deployment and CI/CD pipelines for zero-downtime releases.",
    techStack: ["Next.js", "TypeScript", "Gin (Golang)", "Docker", "CI/CD"],
    features: [
      "Zero-downtime deployment",
      "Blue-green strategy",
      "Fullstack architecture",
      "CI/CD automation",
    ],
    image: "/ara.png",
    link: "https://ara-its.id",
  },
  {
    id: "2",
    title: "Himpunan Mahasiswa Teknologi Informasi",
    role: "Website Project Manager",
    year: "2025",
    description:
      "Managed separate frontend and backend repositories using Next.js and Express.js. Enforced code quality via Husky and GitHub Actions with VPS deployment.",
    techStack: [
      "Next.js",
      "Express.js",
      "TypeScript",
      "Framer Motion",
      "CI/CD",
    ],
    features: [
      "CI/CD workflows",
      "Framer Motion UI",
      "VPS deployment",
      "Code review standards",
    ],
    image: "/hmit.png",
    link: "https://hmit-its.com",
  },
  {
    id: "3",
    title: "ARJUNA Dashboard",
    role: "Website Developer",
    year: "2025",
    description:
      "2nd Place Winner at GEMASTIK Smart City. Built a prototype flood mitigation dashboard featuring 3D map visualizations using Mapbox GL and public API integration.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Mapbox GL"],
    features: [
      "3D visualizations",
      "Real-time flood data",
      "Interactive map layers",
      "Infrastructure automation",
    ],
    image: "/arjunad.png",
    link: "https://arjuna-dashboard.vercel.app",
  },
  {
    id: "4",
    title: "ARJUNA Siaga",
    role: "Mobile Developer",
    year: "2025",
    description:
      "2nd Place Winner at GEMASTIK Smart City. Developed a prototype React Native app for citizen flood reporting with interactive google maps integration and reporting workflow.",
    techStack: ["React Native", "TypeScript", "CSS"],
    features: [
      "Citizen reporting system",
      "Interactive map visualization",
      "Staff workflow dashboard",
      "Real-time reporting",
    ],
    image: "/arjunasiaga.png",
  },
  {
    id: "5",
    title: "SRE ITS",
    role: "Frontend Manager",
    year: "2025-2026",
    description:
      "Supervised frontend development and conducted code reviews across the team. Contributed to membership registration feature integration using Next.js and secure backend APIs.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "React Query"],
    features: [
      "Team supervision",
      "Workflow management",
      "Membership API integration",
      "Frontend architecture",
    ],
    image: "/sre.png",
    link: "https://sre-its.com",
  },
  {
    id: "6",
    title: "FridgeSense",
    role: "Mobile Developer",
    year: "2025",
    description:
      "Developed a full-stack React Native prototype for food shelf-life detection using an AI model, enabling freshness identification, inventory management, and AI-powered recipe recommendations.",
    techStack: ["React Native", "TypeScript", "Python"],
    features: [
      "AI freshness detection",
      "Inventory tracking",
      "Recipe generation",
      "Mobile prototype",
    ],
    image: "/fridgesense.png",
  },
  {
    id: "7",
    title: "WordIT",
    role: "Frontend Developer",
    year: "2025",
    description:
      "Established the frontend foundation for final project, including architecture setup, reusable components, and linting standards, while implementing quiz gameplay, giving reviews, and managing pull requests.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "Axios", "ESLint"],
    features: [
      "Frontend architecture",
      "Quiz game mechanics",
      "Pull request management",
      "Reusable components",
    ],
    image: "/wordit.png",
    link: "https://wordit.it-its.id",
  },
  {
    id: "8",
    title: "SustainaMap",
    role: "Frontend Developer",
    year: "2025",
    description:
      "3rd Place Winner at FIT Competition Hackathon. Built a sustainability-focused web app in 12 hours featuring air quality analysis, environmental scoring, and interactive map layers using Leaflet.",
    techStack: ["Next.js", "TypeScript", "Google Maps Places API", "Leaflet"],
    features: [
      "12-hour development",
      "Interactive maps",
      "Environmental score logic",
      "Location suggestions",
    ],
    image: "/sustainamap.png",
  },
  {
    id: "9",
    title: "Ini Lho ITS 2025",
    role: "Expert Frontend Developer",
    year: "2024",
    description:
      "Implemented pixel-perfect dashboards and landing pages for ILITS, a platform helping students explore their interests at ITS through open campus events and tryout programs.",
    techStack: ["Next.js", "Tailwind CSS", "React Query", "TypeScript", "AOS"],
    features: [
      "Admin & user dashboards",
      "React Query integration",
      "Pixel-perfect UI",
      "Knowledge sharing",
    ],
    image: "/ilits.png",
    link: "https://ilits2025-frontend-dev.vercel.app",
  },
  {
    id: "10",
    title: "Steam Review Spam & Bot Detection",
    role: "Big Data Final Project",
    year: "2024",
    description:
      "Built a hybrid streaming and batch architecture prototype for review spam and bot detection, developing ingestion pipelines with Kafka, storage with MinIO, and preprocessing with PySpark.",
    techStack: ["Python", "PySpark", "Kafka", "MinIO", "Trino"],
    features: [
      "Hybrid data pipeline",
      "Real-time ingestion",
      "Big data preprocessing",
      "Analytical querying",
    ],
    image: "/steam.png",
  },
  {
    id: "11",
    title: "A Renewal Agent 6.0",
    role: "Expert Frontend Developer",
    year: "2024",
    description:
      "Developed a competition website interface, implementing pixel-perfect landing pages and integrating participant registration and dashboard features.",
    techStack: [
      "Next.js",
      "TypeScript",
      "Tailwind CSS",
      "shadcn/ui",
      "React Query",
    ],
    features: [
      "shadcn/ui components",
      "Registration flows",
      "Rapid development",
      "API integration",
    ],
    image: "/ara6.png",
    link: "https://ara6-frontend.vercel.app",
  },
  {
    id: "12",
    title: "Futurest 2025",
    role: "Expert Frontend Developer",
    year: "2024",
    description:
      "Implemented UI slicing for admin and user dashboards, and integrated competition registration features, and conducted code reviews to ensure quality for Futurest 2025.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "React Query"],
    features: [
      "Registration dashboards",
      "Custom link shortener",
      "Secure authentication",
      "State management",
    ],
    image: "/futurests.png",
    link: "https://frontend-futurest2025.pages.dev",
  },
  {
    id: "13",
    title: "Petrolida 2025",
    role: "Frontend Developer",
    year: "2024",
    description:
      "Developed an admin dashboard for Petrolida 2025, implementing UI slicing, data integration for city tours, competitions, and merchandise management, and adding filtering and sorting features",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "React Query"],
    features: [
      "Admin management tools",
      "Data filtering",
      "Merchandise tracking",
      "Responsive dashboard",
    ],
    image: "/petrol.png",
    link: "https://petrolida2025-fe.vercel.app",
  },
  {
    id: "14",
    title: "SRE ITS",
    role: "Frontend Developer",
    year: "2024-2025",
    description:
      "Implemented UI slicing and integrated member pages for an organization website, building responsive interfaces with Next.js and Tailwind CSS to help users get to know the organization.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "React Query"],
    features: [
      "Responsive UI building",
      "Cross-team collaboration",
      "Frontend feature delivery",
      "Design implementation",
    ],
    image: "/sre.png",
    link: "https://sre-its.com",
  },
  {
    id: "15",
    title: "IMAC ITS SB",
    role: "Frontend Developer",
    year: "2024",
    description:
      "Built a responsive landing page for IMAC ITS SB, showcasing the organization's profile and activities, translating UI/UX mockups into interactive web interfaces using Next.js and TypeScript.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    features: [
      "Mockup-to-interface",
      "Responsive design",
      "Interactive components",
      "Performance optimization",
    ],
    image: "/imacsb.png",
    link: "https://silver-tribble-theta.vercel.app",
  },
  {
    id: "16",
    title: "The Cozy Cup",
    role: "Class Project Developer",
    year: "2023",
    description:
      "Built a website for a Website Programming practicum class. Designed the full layout and sliced the UI into functional, responsive components using pure HTML and CSS.",
    techStack: ["HTML", "CSS"],
    features: [
      "Full layout design",
      "UI slicing to components",
      "Responsive web design",
      "Frontend implementation",
    ],
    image: "/cozycup.png",
    link: "https://thecozycup.vercel.app",
  },
  {
    id: "17",
    title: "A Renewal Agent 5.0",
    role: "Frontend Developer",
    year: "2023",
    description:
      "Implemented UI component slicing and integrated a merchandise page for A Renewal Agent 5.0, a competition website held by Information Technology ITS, using Next.js and Tailwind CSS.",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS"],
    features: [
      "First Next.js project",
      "UI/UX collaboration",
      "Component development",
      "Performance learning",
    ],
    image: "/ara5.png",
    link: "https://ara5-frontend-main.vercel.app",
  },
];
